//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTaken
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersoneelsLid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersoneelsLid()
        {
            this.Ondergeschikten = new HashSet<PersoneelsLid>();
        }
    
        public int PersoneelsNr { get; set; }
        public string Voornaam { get; set; }
        public Nullable<int> ManagerNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersoneelsLid> Ondergeschikten { get; set; }
        public virtual PersoneelsLid Manager { get; set; }
    }
}
